language: python
python:
- 2.6
- 2.7
env:
  matrix:
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.0
  global:
  - ARTIFACTS_S3_BUCKET=plone.app.multilingual
  - secure: nIhZCx2JXPSBllk9wQEscZ6qwRtQ2Z8gWZOTipVDjKCnls0J/qthd6svAVW3S+smHwWuQKMogym5xYWbH1kGbE/EZgYZJV4N8vDodpcbpW6HS2O85Zlb2PYcLMcxGy22RRahvJ39TaPMsq7uQMQA7rzZsLFlBxx3FSKd6pDUEE0=
  - secure: fFW5rZPBumVoho2bHaTRyzOZr/2ZCQtwnCqobjnTxf6Upv4qf46Mqg+OApDhMo75Plqt+KupVO9gkYYK4IEoMxinUwxK0Weo51xiUZG3v3PR+vyj4BM1iNlwvzVvQg30FBDGB/a+DuhvQHeCvXE9pgcU3lXkLdO6UK7Xpc+qB7Q=
matrix:
  allow_failures:
  - python: 2.6
    env: PLONE_VERSION=4.2
  - python: 2.7
    env: PLONE_VERSION=4.2
  - python: 2.7
    env: PLONE_VERSION=5.0
  exclude:
  - python: 2.6
    env: PLONE_VERSION=4.3
  - python: 2.6
    env: PLONE_VERSION=5.0
install:
- sed -ie "s#test-plone-4.x.cfg#test-plone-$PLONE_VERSION.x.cfg#" travis.cfg
- mkdir -p buildout-cache/downloads
- python bootstrap.py --setuptools-version=8.3 --version=2.3.1 -c travis.cfg
- bin/buildout -N -t 3 -c travis.cfg
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: bin/test --all -s plone.app.multilingual -t \!\#Plone5
after_script:
- gem install --version 0.8.9 faraday
- gem install travis-artifacts
- travis-artifacts upload --path parts/test
