sudo: false
language: python
addons:
  artifacts:
    paths:
    - parts/test
cache:
  directories:
  - buildout-cache
python:
- 2.6
- 2.7
env:
  matrix:
  - PLONE_VERSION=4.1
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3
  global:
  - ARTIFACTS_KEY=AKIAJP4TGKGJABPQ7YVA
  - ARTIFACTS_BUCKET=plone-app-multilingual
  - ARTIFACTS_CACHE_CONTROL=public
  - ARTIFACTS_PERMISSIONS=public-read
  - secure: "cTwAxlU9LxjLxQ8Gl4yUGKFmvsZmsAQlsRQQ3jwalnYT3ZHFlt3wxEe4u09Foj0ZTst9HWjfVc22sIHX9xiI96cS770uEjPY0Xc5jYidBGHG3FIcYpEAOcWbyF0tAfiQKTuxfR6lGIDcWzjF4Aj8dOAQ4tGBN0eg1OPUEQ9lzmY="
matrix:
  allow_failures:
  - python: 2.6
    env: PLONE_VERSION=4.1
  exclude:
  - python: 2.7
    env: PLONE_VERSION=4.1
  - python: 2.6
    env: PLONE_VERSION=4.2
  - python: 2.6
    env: PLONE_VERSION=4.3
install:
- sed -ie "s#test-plone-4.x.cfg#test-plone-$PLONE_VERSION.x.cfg#" travis.cfg
- mkdir -p buildout-cache/downloads
- python bootstrap.py -c travis.cfg
- bin/buildout -Nc travis.cfg annotate
- bin/buildout -Nc travis.cfg
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: bin/test --all -s plone.app.multilingual
notifications:
  irc:
    channels:
    - irc.freenode.org#plone-testing
    template:
    - "%{repository}#%{build_number} (%{branch} | %{commit} | %{author}): %{message}"
    - "Robot: http://plone.app.multilingual.s3-website-us-east-1.amazonaws.com/artifacts/%{build_number}/%{build_number}.1/robot_report.html"
